# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version = "10.0.3";
      src = {
        rev = "1d69e55fc60915f8f1569c9f6522d9b0fb5a0ba8";
        sha256 = "0ldaj072x16452xw2wszbk20g932rz36zappjrxc4m6ygx298aa3";
      };
    };
    libVersion = {
      version = "10.0.3";
      libSources = {
        symbols.rev = "299c330ab364cfc3989d1ab6e82f1eabb9ddd915";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "a7e1a3ae6255d8d9aaff13e58adf3a0d78cb90c9";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "fe0ca39d34a10036f2b6ccb9749a39bc3fa7af95";
        footprints.sha256 = "0wdzsn7z11wc5yskk576a4a6qfagsvw0y6r034inxrnfc32aiah9";
        packages3d.rev = "c955b94c7bdeffd94b06bac86d94588a9be03afe";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version = "10.0-2026-05-30";
      src = {
        rev = "81d0ec2f35bd2ce905e006d38274a5ab37d6baa9";
        sha256 = "1ajnh1d8gpyyh53s766cr7n6x3h4z0hrlhmyi9dx86p4c6138qly";
      };
    };
    libVersion = {
      version = "10.0-2026-05-30";
      libSources = {
        symbols.rev = "299c330ab364cfc3989d1ab6e82f1eabb9ddd915";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "a7e1a3ae6255d8d9aaff13e58adf3a0d78cb90c9";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "fe0ca39d34a10036f2b6ccb9749a39bc3fa7af95";
        footprints.sha256 = "0wdzsn7z11wc5yskk576a4a6qfagsvw0y6r034inxrnfc32aiah9";
        packages3d.rev = "c955b94c7bdeffd94b06bac86d94588a9be03afe";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version = "2026-06-21";
      src = {
        rev = "ca930dd5e86f9f38b52feb60466090946fda930c";
        sha256 = "038fds1qw92962y65yrhzbjkxjfhkm550dd0b7ivpkm8m8db0cs8";
      };
    };
    libVersion = {
      version = "2026-06-21";
      libSources = {
        symbols.rev = "c7e226a4946cbd123ac57131b79a73979891d82f";
        symbols.sha256 = "0sj2kxr48wqz075fda6jiwk9ajdf6iirbiw92wlilq3w8i3xa431";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "645402ed82e16096cf827fea7114fdbef4c46948";
        footprints.sha256 = "0plw6h6vr3rj9y7i59wa9c9qx9l8lsvzgan48q2k87wbs4x1gwsl";
        packages3d.rev = "0bc64e922178140eb6890377646efd45e15011bd";
        packages3d.sha256 = "0mkc9km540n6ri5is4fjw5abv8afidwj9q7fmbs66l6kx1z3lxky";
      };
    };
  };
}
